CREATE TABLE BelastingTelefoon (
    Jaar INT,
    Kwartaal INT,
    JaarMaand VARCHAR(7) CHARACTER SET utf8,
    Maand INT,
    JaarWeek INT,
    Week INT,
    Date DATETIME,
    Uur INT,
    Uur_15min INT,
    Werkstroom VARCHAR(40) CHARACTER SET utf8,
    Contactthema VARCHAR(40) CHARACTER SET utf8,
    V_Aanbod INT,
    Calls_Short_Abandoned INT,
    V_Abandoned INT,
    Calls_Answered INT,
    Calls_Answered_Threshold INT,
    Wait_Time_to_Answer INT,
    Time_to_Abandon INT,
    Geweigerde_aantallen INT,
    Aantal_Herr_Naar_CT_kwart INT,
    V_Aangenomen NUMERIC(5, 3),
    V_SL NUMERIC(5, 3)
);