CREATE TABLE BelastingTelefoon (
    Jaar NUMERIC(5, 1),
    Kwartaal NUMERIC(2, 1),
    JaarMaand VARCHAR(7) CHARACTER SET utf8,
    Maand NUMERIC(2, 1),
    JaarWeek INT,
    Week NUMERIC(3, 1),
    Date DATETIME,
    Uur INT,
    Uur_15min INT,
    Werkstroom VARCHAR(4) CHARACTER SET utf8,
    Contactthema VARCHAR(11) CHARACTER SET utf8,
    V_Aanbod NUMERIC(3, 1),
    Calls_Short_Abandoned NUMERIC(2, 1),
    V_Abandoned NUMERIC(2, 1),
    Calls_Answered NUMERIC(3, 1),
    Calls_Answered_Threshold NUMERIC(3, 1),
    Wait_Time_to_Answer NUMERIC(4, 1),
    Time_to_Abandon NUMERIC(2, 1),
    Geweigerde_aantallen NUMERIC(2, 1),
    Aantal_Herr_Naar_CT_kwart NUMERIC(2, 1),
    V_Aangenomen NUMERIC(2, 1),
    V_SL NUMERIC(13, 12)
);